package com.kakao.jaypark.grapesticker.core.domain

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.kakao.jaypark.grapesticker.core.domain.converter.LocalDateTimeConverter
import com.kakao.jaypark.grapesticker.core.domain.generator.CreatedDateGenerator
import org.springframework.data.annotation.Id
import java.time.LocalDateTime

@DynamoDBTable(tableName = "bunch-member")
data class BunchMember(
        @Id
        @DynamoDBIgnore
        val key: BunchMemberKey = BunchMemberKey(),

        @DynamoDBAttribute
        @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
        @DynamoDBAutoGenerated(generator = CreatedDateGenerator::class)
        var createdDate: LocalDateTime? = null,
        @DynamoDBAttribute
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
        var type:MemberType = MemberType.MASTER
){
        @DynamoDBHashKey
        @DynamoDBIndexRangeKey(globalSecondaryIndexName = "idx-by-memberId")
        fun getBunchId() = key.bunchId.orEmpty()

        fun setBunchId(bunchId: String) {
                key.bunchId = bunchId
        }

        @DynamoDBRangeKey
        @DynamoDBIndexHashKey(globalSecondaryIndexName = "idx-by-memberId")
        fun getMemberId() = key.memberId.orEmpty()

        fun setMemberId(memberId: String) {
                key.memberId = memberId
        }
}