package com.kakao.jaypark.grapesticker.core.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "bunch")
data class Bunch(
        @DynamoDBHashKey(attributeName = "id")
        @DynamoDBAutoGeneratedKey
        var id: String? = null,
        @DynamoDBAttribute
        var name: String,
        @DynamoDBAttribute
        var maxNumberOfGrapes: Int = 10,
        @DynamoDBAttribute
        var grapes: Set<Grape>? = null
) {

}