package com.kakao.jaypark.grapesticker.core.domain

import com.amazonaws.services.dynamodbv2.datamodeling.*

@DynamoDBTable(tableName = "member")
data class Member(
        @DynamoDBHashKey(attributeName = "id")
        @DynamoDBAutoGeneratedKey
        var id: String? = null,
        @DynamoDBAttribute
        var email:String,
        @DynamoDBAttribute
        var name:String,
        @DynamoDBAttribute
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
        var type:MemberType = MemberType.MEMBER
)
