package com.kakao.jaypark.grapesticker.core.domain

import com.amazonaws.services.dynamodbv2.datamodeling.*

@DynamoDBTable(tableName = "member")
data class Member(
        @DynamoDBHashKey(attributeName = "id")
        @DynamoDBAutoGeneratedKey
        var id: String? = null,
        @DynamoDBAttribute
        @DynamoDBIndexHashKey(globalSecondaryIndexName = "idx-member-email", attributeName = "email")
        var email:String?=null,
        @DynamoDBAttribute
        var name:String?=null
)
