spring:
  profiles:
    include: default
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 1
        writeCapacity: 1

amazon:
  dynamodb:
    endpoint: "http://localhost:8000"
    region: "ap-northeast-2"
    tablePrefix: "grape-sticker"
    tableSuffix: "test"
  aws:
    accesskey: "test"
    secretkey: "test"
